### ISSUE TITLE
JATS4R tag: how should documents self-identify that they conform?

### ISSUE THREAD

**Issue by Klortho** [JATS4R/elements#10]
This came up in our last telecon.  It's important, so that bots harvesting content from disparate sources would know which documents they can "trust".

I haven't looked this over in detail, but we could perhaps adopt the mechanism in the PMC tagging guidelines, [Associating Schemas](http://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/genprac.html#schemas)

**Comment by Melissa37** [comment]
We at eLife like the recommendation for versioning. However, we need to ensure we document it somewhere on the website for users.
Also, the one line of code validating against the one version of JATS4R version is much preferable, the other method would deffo be too cumbersome for publishers and their hosts to implement. Also picking and choosing would be too hard for the data miners to administer as well?
The tool would need to allow users to pick the version to validate against.

**Comment by Klortho** [comment]
> When Oxygen finds an <?xml-model?> in an article with a DOCTYPE declaration, the DOCTYPE is ignored and the schema called by the xml-model pi is applied.

That's a pretty nasty problem.  Maybe they oxygen developers could be persuaded to add an option to control this?

**Comment by Klortho** [comment]
I think we agreed at the meeting that Jeff's suggestions above are good, sans the "phase" examples. That is, just keep the self-identification (the \<?xml-model?> PI) to a simple syntax that identifies the particular recommendations.
Allowing more control in the validator would be fine, but it's a separate issue.

**Comment by Klortho** [comment]
What about the URI that identifies the schematron?  Jeff suggested "http://jats4r.org/schematron/jats4r-0.1.sch".  Comments:

* Are we going to get jats4r.org?  It is available, and it should be easy to have this [custom domain set up with our github pages](https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/)
* I'd suggest changing "schematron" to "schema". We might want to put other types of schema files in there
* How about putting the version number into a path segment? It will probably make it easier to handle for releases, I think.

So, I'm suggesting "http://jats4r.org/schema/0.1/jats4r.sch"

**Comment by Klortho** [comment]
I created a wiki page for this: https://github.com/JATS4R/elements/wiki/JATS4R-schema-processing-instruction

**Comment by Melissa37** [comment]
Update the example in the paper
Put the new url in the schematron "stuff"

**Comment by Klortho** [comment]
I reorganized things in the repository a bit, so that the schematron files are in locations that match the URL that we agreed on.

That URL is "http://jats4r.org/schema/0.1/jats4r.sch".  This should be persistent and stable, and it is serving the proper schematron file right now.

After reorganizing, I added a description of the directory structure [to the README](https://github.com/JATS4R/jats4r.github.io#directories-and-files) and got everything working again.

**Comment by Klortho** [comment]
I'll close this, since this issue itself is resolved, but I'll open another issue on establishing recommendations for, in general, how documents should be structured.  In other words, in addition to "permissions" and "math", we need a recommendations topic that covers adding this PI, as well as other issues.
