### ISSUE TITLE
Contribution to JATS-Con 2015

### ISSUE THREAD

**Issue by Daniel-Mietchen** [JATS4R/elements#16]
It would be nice to prepare a JATS4R contribution to JATS-Con.

Submissions are due by November 14:
http://jats.nlm.nih.gov/jats-con/forms/JATSsubmission.html .

That fits with our original plan of having something ready by Open Access Week, which is three weeks earlier.

Google doc for draft of our paper: [Improving the reusability of JATS](https://docs.google.com/document/d/15uB0B97_fCiABloarb0OHL5doyEvdXLJmirwMtOWSHQ/edit)

**Comment by Melissa37** [comment]
Thanks for posting the reviews Daniel. This is useful info to help shape the paper.

**Comment by Klortho** [comment]
I created a Google doc for this here: [Improving the reusability of JATS](https://docs.google.com/document/d/15uB0B97_fCiABloarb0OHL5doyEvdXLJmirwMtOWSHQ/edit). Right now it is not much more than a skeleton.  Please hack away.

**Comment by Melissa37** [comment]
Beginnings of the slides are here
https://docs.google.com/a/elifesciences.org/presentation/d/17dIbIRlLJ6sBQh_gAxX9izm6yaZoFAk9RRLo2QaOSng/edit#slide=id.g8fd38d72c_0_165

Needs work and input form other presenters!
