### ISSUE TITLE
Licensing of license statements

### ISSUE THREAD

**Issue by Daniel-Mietchen** [JATS4R/elements#24]
We have now started a project to map text-based license statements to license URLs: https://github.com/wpoa/Open-License-Dictionary . This [raised the question](https://github.com/wpoa/recitation-bot/issues/29#issuecomment-57515515) under what license these license statements can be aggregated and shared.

Any pointers appreciated.

**Comment by jeffbeckncbi** [comment]
This is an interesting question, but I'd like to close this issue - or at least disassociate it from what we need to get done for the "permissions" task. I don't think it will have an effect on the JATS4R recommendations.
