### ISSUE TITLE
<copyright-year> and <copyright-holder> recommendations

### ISSUE THREAD

**Issue by Klortho** [JATS4R/elements#26]
I just [added two paragraphs](https://github.com/JATS4R/elements/wiki/Permissions/_compare/6f1cbed3ccfb39aaf85a46ae0184d74e12a0d175...163b50bf3e30e98f2f3ed9574d77097dfc2b3559) to the permissions wiki page referring to the \<copyright-year> and \<copyright-holder> elements (the first and second paragraphs [here](https://github.com/JATS4R/elements/wiki/Permissions#recommendations)).  Any objections or discussion?

**Comment by pdonohoe** [comment]
I agree as it is written.

**Comment by Melissa37** [comment]
We agree too

**Comment by Melissa37** [comment]
Should the copyright year be 2015-01-22 (ISO 8601). Jeff, I noticed for the validation your requirement is a  4-digit integer. Does that fit with this?

**Comment by hubgit** [comment]
The copyright year should be a year :)

**Comment by Melissa37** [comment]
Durhhh!!!!
Sorry :-) Getting a bit carried away there.
