### ISSUE TITLE
Access License and Indicators Working Group: <free-to-read>

### ISSUE THREAD

**Issue by Melissa37** [JATS4R/elements#33]
http://www.niso.org/apps/group_public/download.php/14226/rp-22-2015_ALI.pdf

Last time this was discussed on the JATS list was Jan 2014. 

Looks like this is now recommended practice - will it be included in JATS?

**Comment by jats-laura** [comment]
Yes. The Standing Committee has been postponing decisions on the license-related issues until this was finalized. Now that it is, the SC will review it and incorporate the practices into the next JATS version, which is hopefully the one that will become the next version of the standard.

**Comment by Melissa37** [comment]
Has this been incorporated yet?

**Comment by Melissa37** [comment]
This is an interesting read:

http://blog.wellcome.ac.uk/2015/03/03/the-reckoning-an-analysis-of-wellcome-trust-open-access-spend-2013-14/

The report highlights one of the issues in non-compliance as:
Contradictory licence information (the human readable text says one licence, the licence encoded in the XML cites a different one);

**Comment by Melissa37** [comment]
And another:
http://www.rcuk.ac.uk/RCUK-prod/assets/documents/documents/Openaccessreport.pdf

... There are ways to protect third party
material even within a CC-BY-licensed article, but this is
not well-understood by all rights-owners, and the issue will
take some time to be resolved. These issues surrounding
securing image rights and third party copyright also add to
the confusion around the use of licences and what can and
cannot be done under particular licences. Similarly, Taylor
and Francis also highlighted evidence they had of not being
able to secure third party copyrights for articles containing
sheet music and images of art. This has meant that, as they
could not secure the correct rights, they could not publish
the article under a CC-BY licence so they did not proceed
to publish the article. PLOS, who require CC-BY for all their
content, have worked with publishers to make non-CC-BY
content on other publisher platforms available under CCBY
licence19. The panel recommends that there may be an
opportunity for RCUK to learn from this experience.

**Comment by Melissa37** [comment]
Closed. Superseded by #50
