### ISSUE TITLE
Questions about draft recommendations - Math

### ISSUE THREAD

**Issue by Melissa37** [JATS4R/elements#34]
Peter Krautzberger:

I've looked through the threads -- apologies if I may have missed a discussion.

I wanted to discuss https://github.com/JATS4R/elements/wiki/Math.

First, I'm wondering why point 3) uses "either or" for markup. It seems like alternatives for markup are preferable (MathML, TeX, SSML etc.)?

Second, I've been wondering about best practices for &lt;tex-math> content. In the JATS documentation the example is a full-fledged LaTeX documents. Is this the intent of the spec? Is it (best) practice? I've encountered mostly math-mode LaTeX content in tex-math elements (but of course that leads to the problem of macros and packages).

Finally, I've been wondering about best practices for mathematical content beyond formulas. &lt;statement> seems to be made for most theorem-like environments. Is that the best practice (for reuse)?

Are there good use cases outside of mathematics? I know some examples from Law but my knowledge of real STEM world content is limited.

BTW, the W3C DPUB IG is working with the WAI WG to add new ARIA roles for structural semantics. I'm proposing a "statement" role and it would be good to have more STEM use cases to bolster this.

Best regards,
Peter.

**Comment by Melissa37** [comment]
Kaveh Bazargan:

You are right that if it is TeX for math, it must be guaranteed that it is self contained and not relying on macros which might have gone missing. I would suggest the default, and the best practice format is MathML, which is by definition the way to hold math in XML. Any other formats can be included, but there must be a definitive version, so if in 10 years time we find all alphas in MathML are beta in TeX, there is no doubt as to which is correct. 

There are instances where MathML is not rich enough to hold the math, in which case TeX can be used, with a graphic fallback.

**Comment by pkra** [comment]
In reply to Kaveh.

> You are right that if it is TeX for math, it must be guaranteed that it is self contained and not relying on macros which might have gone missing. 

How feasible is this? Is there extensive experience with re-using such full TeX documents coming from random jats content?  I've come across only a few examples of this (and more  examples of using math mode fragments). From that experience it's not a very reliable way for enabling reuse (or preservation actually -- the full document fragments were less likely to compile than the fragments).

I'm not sure if that leads to the ultimate problem that TeX is a programming language which means to reproduce we need a copy of the compiler -- ok, not really, but a copy of "everything", i.e., the packages (and versions), the TeX version/variant etc.

I suspect that in reality, people normalize TeX during conversion to jats in which case it would be useful to specify the normalized level in jats4r (e.g., a list of suggested packages). If jats4r wants to improve, well, reuse, then I suspect "full TeX document" is not a good choice.

> I would suggest the default, and the best practice format is MathML,[...]

Naturally, I tend to agree. But I know a few people who might see TeX authoritative.

> Any other formats can be included, but there must be a definitive version [...]

Good point. Is there a preferred way to identify that?

> There are instances where MathML is not rich enough to hold the math, in which case TeX can be used, with a graphic fallback.

Personally, I'd prefer to represent such cases in HTML5 / HTML, CSS, SVG, MathML.

**Comment by Nikos-Markantonatos** [comment]
> You are right that if it is TeX for math, it must be guaranteed that it is self contained and not relying
> on macros which might have gone missing.

When you are encoding under LaTeX, you have to rely on packages, which however may be hard to locate in the future. Yet, most publishers/typesetters hate to include the LaTeX preamble where all definitions are taking place in the XML and just wish to encode the actual equation with all the environment implied.

MathJAX is giving the wrong example by allowing TeX/LaTeX to be processed in exactly this manner (such the code for the equation), but whatever implicit assumptions are made by such tools can hardly be considered as leading to an archival quality XML.

> There are instances where MathML is not rich enough to hold the math, in which case TeX can
> be used, with a graphic fallback.

I think MathML is rich enough to represent any math. The opposite, however, is not true. f you get into the business of converting MathML into LaTeX you soon run out of options.

**Comment by pkra** [comment]
> but whatever implicit assumptions are made by such tools can hardly be considered as leading to an archival quality XML.

I was under the impression that JATS4Reuse was about, well, re-use, not archival. For re-use a clearly specified subset of math-mode LaTeX could go a long way (including some outlines on enabling macro resolution that is neither too coarse nor too thin). Wikipedia's texvc is an interesting example.

> I think MathML is rich enough to represent any math. 

I don't think even the MathWG would make that claim ;-) Something as basic as a commutative diagram quickly runs into limitations of the spec.

> The opposite, however, is not true. f you get into the business of converting MathML into LaTeX you soon run out of options.

Do you mean that reusabiility is limited or that conversion is? While I haven't extensively used it, I was under the impression that David Carlisle's [pmm2tex](https://code.google.com/p/web-xslt/source/browse/#svn%2Ftrunk%2Fpmml2tex) works well for conversion (though maybe not for reuse).

**Comment by Nikos-Markantonatos** [comment]
> I was under the impression that JATS4Reuse was about, well, re-use, not archival.

Perhaps this is a larger philosophical discussion, but I wouldn't want to sacrifice XML archivability over re-use.

> Do you mean that reusabiility is limited or that conversion is?

I was referring to the MathML conversion into LaTeX.

**Comment by pkra** [comment]
> Perhaps this is a larger philosophical discussion, but I wouldn't want to sacrifice XML archivability over re-use.

I would agree. But I don't quite see how a recommendation for providing an alternative for re-use sacrifices an alternative for archival.

> I was referring to the MathML conversion into LaTeX.

Thanks for clarifying. As I wrote, I thought pmml2tex solves that part. Is that inaccurate?

**Comment by Nikos-Markantonatos** [comment]
> But I don't quite see how a recommendation for providing an alternative for re-use sacrifices an
> alternative for archival.

Are you implying two alternative encodings for equations? I, for one thing, would much prefer a single encoding covering both needs. Most publishers will be unhappy to be asked to maintain two alternative encodings for their equations.

> As I wrote, I thought pmml2tex solves that part. Is that inaccurate?

It probably does, I am not aware of this tool, but it seems counter-intuitive that you would have MathML and wish to move to TeX for re-usability.

**Comment by pkra** [comment]
> It probably does, I am not aware of this tool, but it seems counter-intuitive that you would have MathML and wish to move to TeX for re-usability.

I was merely replying to your earlier comment on reuse of MathML in TeX. Sorry if this derailed the discussion.

**Comment by Klortho** [comment]
I just read through this discussion, and want to take a stab at summarizing the open questions. I'm not a TeX/LaTeX expert, so I may have misunderstood some bits.

A. Do we insist on MathML, or do we also allow TeX?  I think the answer is probably, allow TeX.
B. If we allow TeX, do we want to specify that the content of the  <tex-math> element should be math-mode LaTeX fragments (i.e. not complete documents), or do we allow complete documents (such as [the example in the [&lt;tex-math> documentation](http://jatspan.org/niso/publishing-1.1d1/#p=elem-tex-math))?
C. If we allow complete documents, do we want to specify some normalized subset of packages that are allowed? (That would address both the issues of reusability and archiving, I think.)
D. If we allow math-mode LaTeX fragments, then do we somehow specify a subset, or a context in which these are interpreted?  Peter mentioned [Mediawiki's texvc](http://www.mediawiki.org/wiki/Texvc), and that looks interesting.

**Comment by pkra** [comment]
I think that sums it up.

I would add my question about non-equational math content (Theorems, Definitions etc). I don't know if I screwed up my OP to the mailing list or if it was lost in copy&paste but I had wondered about the `statement` element and whether it is considered best practice (and where else in STEM content it might be used).

**Comment by Klortho** [comment]
Ah, I see that you neglected to xml-escape the element tags in your OP. Markdown let's you add arbitrary HTML, so you have to remember to escape &lt; as &amp;lt; when writing a tag. It makes more sense to me, now.

**Comment by pkra** [comment]
Yup. I didn't author the OP so can't fix it :-)

**Comment by Klortho** [comment]
I think this is superceded by some other, more specific issues. Reopen if you disagree.
