### ISSUE TITLE
Math recommendations point 2

### ISSUE THREAD

**Issue by Melissa37** [JATS4R/elements#38]
There should only be one expression tagged in any &lt;inline-formula> or &lt;disp-formula>.

What is defined as an expression?

**Comment by Klortho** [comment]
If you look at the content model for [&lt;disp-formula>](http://jatspan.org/niso/publishing-1.1d1/#p=elem-disp-formula), for example, you'll see that it allows any number of child &lt;tex-math> and/or &lt;mml:math> elements (not to mention any number of other things).

I think this recommendation could be tightened to specify the content models of <inline-formula> and <disp-formula> more rigorously: i.e. that they must only contain one &lt;tex-math>, one &lt;mml:math>, ***or*** one &lt;alternatives&gt;. If the latter, then the &lt;alternatives> must have one &lt;tex-math> or one &lt;mml:math> (but not both) and one &lt;graphic&gt;.

**Comment by jats-laura** [comment]
>If the latter, then the <alternatives> must have one <tex-math> or one <mml:math> (but not both) and one <graphic>.

I disagree with limiting &lt;alternatives> to having *either* &lt;tex-math> *or* &lt;mml:math>. I believe there are legitimate use cases for having both.

**Comment by Klortho** [comment]
That makes sense to me.

**Comment by jeffbeckncbi** [comment]
Updated Recommendation #2 to:

There should be one and only one expression tagged in each <inline-formula> and <disp-formula>. <inline-formula> and <disp-formula> must contain one <tex-math>, one <mml:math>, or one <alternatives>. If <alternatives> is used, each representation within it should be correct and complete and be logically equal. There is no explicit or implied preferred representation within <alternatives>.
