### ISSUE TITLE
Disallow the use of <private-char>

### ISSUE THREAD

**Issue by Klortho** [JATS4R/elements#44]
The [&lt;private-char>](http://jatspan.org/niso/publishing-1.1d1/#p=elem-private-char) element in JATS is designed to allow content creators to use the private-use area (PUA) of Unicode to incorporate characters (glyphs) for which no suitable entry exists in Unicode.

Can we disallow this? It seems that it would make articles exponentially harder to reuse, and, since the time JATS was written, Unicode has come a long way, and perhaps there are many fewer instances where this would be necessary.

If this were disallowed, it would also mean that &lt;glyph-data> and &lt;glyph-ref> would also be omitted.

One exception we might consider is to allow the use of the [Conscript Unicode Registry](http://www.evertype.com/standards/csur/), which would allow the use of [Klingon](http://www.evertype.com/standards/csur/klingon.html) and [http://www.evertype.com/standards/csur/seuss.html](Seussian) characters, but I kind-of doubt there's a significant demand for these.  ;)

**Comment by hubgit** [comment]
Avoiding `<private-char>` [would make re-use easier](http://blogs.ch.cam.ac.uk/pmr/2014/12/15/how-publishers-destroy-science-elseviers-xml-api-and-the-disappearing-chemical-bond-do-not-buy-xml/). It's not entirely clear what to recommend as an alternative, though…

**Comment by jeffbeckncbi** [comment]
I'm not saying we shouldn't disallow &lt;private-char&gt;. But just to clarify.  &lt;private-char&gt; is designed to allow content creators to define a character (including a glyph bitmap) for any character that is not defined by Unicode. 

There is no association with the Private Use Area. The PUA is mentioned because many publisher will define characters in their own publishing systems and include only the PUA character in articles. Anyone trying to reulse the articles has no way of knowing what &#xE000; is supposed to represent.

 &lt;private-char&gt;  is handy way to describe and use characters that are not defined by Unicode. Because the glyph is supplied in the article, there is really no barrier to reuse. Anyone who can read the element will know what the character is. The only complication is developing the software to process the characters for display.

**Comment by doylemd** [comment]
Hmm, well, as the originator of the &lt;private-char&gt; construct (originally from APS proprietary DTD -> NLM -> JATS), I am with Jeff here. Original concept was to have ASCII art (1's and 0's)/bitmap version of glyph embedded so people can understand what the glyph looked like. When converting content from our old DTD to JATS, we captured in a &lt;custom-meta-group&gt; the original private glyph data (ascii art) and then converted the underlying custom font used by the vendor to a font with code points in the PUA (distinct and well separated from the STIX PUA). If there are items within the private font that have versions in the STIX private use area, we used the STIX version (which came after the earliest XML we have). Note that we have used this only about 200 times out of almost 300,000 full text XML files, so pretty rare. PUA for this started at F000.

**Comment by Klortho** [comment]
Alf, I read the PMR post you linked to, and it was avoiding that kind of thing that I had in mind.

But, it sounds like there's still a need for this, so I'll withdraw the suggestion.  Although, it's worth mentioning that in the JATS documentation, the first example is a "NORTHWEST SOUTHEAST ARROW", and a Unicode character does exist for that, [U+2921](http://unicode-table.com/en/2921/).  Not sure whether or not it existed at the time the JATS docs were written, though.

**Comment by hubgit** [comment]
Found an example in[ the JATS documentation for `<alternatives>` (Example 4)](http://jatspan.org/niso/publishing-1.0/#p=elem-alternatives) that seems like what @doylemd is describing:

```xml
<alternatives>
  <textual-form specific-use="unicode-look-alike">&#x2261;</textual-form>
  <private-char name="Triple Bond" description="Chemistry Triple Bond">
    <glyph-data id="tbond" format="PBM" resolution="300" x-size="16" y-size="32">
0000000000000000000000000000000
0000000000000000000000000000000
0000000000000000000000000000000
0000000000000000000000000000000
0000000000000000000000000000000
0001111111111111111111111100000
0000000000000000000000000000000
0000000000000000000000000000000
0001111111111111111111111100000
0000000000000000000000000000000
0000000000000000000000000000000
0001111111111111111111111100000
0000000000000000000000000000000
0000000000000000000000000000000
0000000000000000000000000000000
0000000000000000000000000000000
0000000000000000000000000000000
0000000000000000000000000000000
    </glyph-data>
  </private-char>
</alternatives>
```

**Comment by doylemd** [comment]
Thanks @hubgit  - I should have remembered that was there (it was derived from an early APS example). It also reminded me that I misspoke in the other comment about using custom-meta-group because, of course glyph-data is there.
