### ISSUE TITLE
Should we get the jats4r.org domain?

### ISSUE THREAD

**Issue by Klortho** [JATS4R/elements#46]
Mentioned this on the phone conversation just now. There would be three associated costs:

* domain registration = ~10 / year
* DNS service = there are free services
* hosting = AWS is ~15 / month

**Comment by Daniel-Mietchen** [comment]
Makes sense to me, and I'm confident we can cover those costs. 
See also [custom domains for GitHub Pages sites](https://help.github.com/articles/about-custom-domains-for-github-pages-sites/).

**Comment by Melissa37** [comment]
eLife can cover the costs for this. Chris, do you want to email me separately about this and we'll set it up from the eLife offices so invoices come direct to us? 
M

**Comment by Klortho** [comment]
This is done!  Our site should now be being served from [http://jats4r.org](http://jats4r.org).  Please re-open and put a comment here if you notice any problems.
