### ISSUE TITLE
Update home page - move permissions and licenses, and math formulas from draft to final

### ISSUE THREAD

**Issue by Melissa37** [JATS4R/elements#48]

**Comment by Klortho** [comment]
I got the [permissions](http://jats4r.org/recommendations/permissions.html) and [math](http://jats4r.org/recommendations/math.html) recommendations moved from the wiki to the main site.  The originals are still in markdown format, which is nice. So, transferring them from the GitHub wiki to the main site is pretty painless, and involves these simple steps:

* Add a short YAML block to the top, which gives the page's title
* Changing the code block beginning fence from "xml" to "markup", which is what the prism syntax highlighter wants.

Does anyone have a preference for the URL -- should it be http://jats4r.org/recommendations/math.html or http://jats4r.org/recs/math.html?

**Comment by kaveh1000** [comment]
Great work, Chris!

I personally prefer

 http://jats4r.org/recommendations/math.html

On 18 April 2015 at 05:19, Chris Maloney <notifications@github.com> wrote:

> I got the permissions <http://jats4r.org/recommendations/permissions.html>
> and math <http://jats4r.org/recommendations/math.html> recommendations
> moved from the wiki to the main site. The originals are still in markdown
> format, which is nice. So, transferring them from the GitHub wiki to the
> main site is pretty painless, and involves these simple steps:
>
>    - Add a short YAML block to the top, which gives the page's title
>    - Changing the code block beginning fence from "xml" to "markup",
>    which is what the prism syntax highlighter wants.
>
> Does anyone have a preference for the URL -- should it be
> http://jats4r.org/recommendations/math.html or
> http://jats4r.org/recs/math.html?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JATS4R/elements/issues/48#issuecomment-94124145>.
>



-- 
Kaveh Bazargan
Director
River Valley Technologies
@kaveh1000
+44 7771 824 111
kaveh@rivervalleytechnologies.com
www.rivervalleytechnologies.com

**Comment by Klortho** [comment]
Okay, let's leave it like it is, then.

**Comment by kaveh1000** [comment]
Hi Chris

Just rereading the page, some typos on the math page you put up:


* (for and <inline-formula>) or <graphic> (for a <disp-formula<)*

should read:


* (for an <inline-formula>) or <graphic> (for a <disp-formula>)*

and in the last code snippet,

*<meta-value>*
*      \def\rmi*
*      \def\rme*
*    </meta-value>*

should read

*<meta-value>*
*      \def\rmi{\rm i}*
*      \def\rme{\rm e}*
*    </meta-value>*

Thanks.

Regards
Kaveh

On 18 April 2015 at 05:19, Chris Maloney <notifications@github.com> wrote:

> I got the permissions <http://jats4r.org/recommendations/permissions.html>
> and math <http://jats4r.org/recommendations/math.html> recommendations
> moved from the wiki to the main site. The originals are still in markdown
> format, which is nice. So, transferring them from the GitHub wiki to the
> main site is pretty painless, and involves these simple steps:
>
>    - Add a short YAML block to the top, which gives the page's title
>    - Changing the code block beginning fence from "xml" to "markup",
>    which is what the prism syntax highlighter wants.
>
> Does anyone have a preference for the URL -- should it be
> http://jats4r.org/recommendations/math.html or
> http://jats4r.org/recs/math.html?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JATS4R/elements/issues/48#issuecomment-94124145>.
>



-- 
Kaveh Bazargan
Director
River Valley Technologies
@kaveh1000
+44 7771 824 111
kaveh@rivervalleytechnologies.com
www.rivervalleytechnologies.com

**Comment by Klortho** [comment]
Fixed, thanks.
