### ISSUE TITLE
Validator not reading DTDs

### ISSUE THREAD

**Issue by Klortho** [JATS4R/elements#49]
I don't know if this problem has an easy solution or not, but right now, if you give [the validator](http://jats4r.github.io/validate/) an XML document that relies on the DTD, then it will fail.  For example, the following uses `&mdash;`, which is defined in the DTD:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article 
  PUBLIC "-//NLM//DTD JATS (Z39.96) Journal Publishing DTD v0.4 20110131//EN"
  "../dtd/JATS-journalpublishing0.dtd">

<article>
  <front>
    <journal-meta>
      <journal-id></journal-id>
      <issn></issn>
    </journal-meta>
    <article-meta>
      <article-id>ArchivalTest1</article-id>
      <title-group>
        <article-title>Fleegle and &mdash; friends</article-title>
      </title-group>
      <pub-date>
        <year>2015</year>
      </pub-date>
    </article-meta>
  </front>
</article>
```

This illustrates the rationale behind issue #1. If we're not going to take that suggestion, then we're going to need to fix the validator, and I'm not sure if that will be easy with it's current client-side implementation.

**Comment by Klortho** [comment]
Based on the Saxon-CE page [XML Conformance](http://www.saxonica.com/ce/user-doc/1.1/html/conformance/XML-conformance.html), it looks like Saxon-CE uses the browser's XML parser.

So, the *only* way I can think of to resolve this would be to have a hacky preprocessing step, where the JavaScript examines the beginning of the XML document first. If it finds a doctype declaration, then it could do an ajax request to retrieve a minified version of that DTD from somewhere like [here](https://raw.githubusercontent.com/wendellpiez/oXygenJATSframework/master/O2-DTD/O2-blue-ot.dtd), and stuffs it in as an internal subset.

That idea might actually have some appeal, if the validator would use the DTD to actually, you know, *validate* the document.  But apparently, the browser's parser (at least, Chrome's) doesn't.  I just tried it with [this file](https://gist.github.com/Klortho/684730f1196d6bb56e63), which has a version of the JATS DTD as it's internal subset, but whose content is *not valid*.  The validator was perfectly happy with it.

**Comment by Klortho** [comment]
We could, however, create a version of this internal subset that *just* has the entity definitions (e.g. `<!ENTITY cong "≅">`) and insert that in, when necessary.

**Comment by vincentml** [comment]
One solution would be to recommend using a complete URL instead of a local file reference in the DOCTYPE. Using a local file reference requires the user to have a local copy of the DTD, and probably use a catalog file, or to not validate against the DTD. When the complete URL is used in the DOCTYPE (assuming the URL is stable and the parser is able to access it) the parser can download the DTD if it does not have a local copy available. 

Further, using a relative path as in your example ("../dtd/JATS-journalpublishing0.dtd") causes problems for some parsers / catalog resolvers. It's safer to use just the file name ("JATS-journalpublishing0.dtd") or a complete stable URL in addition to the formal public identifier. 

For example place this in your XML:

<!DOCTYPE article PUBLIC "-//NLM//DTD JATS (Z39.96) Journal Archiving and Interchange DTD v1.1d2 20140930//EN" "http://jats.nlm.nih.gov/archiving/1.1d2/JATS-archivearticle1.dtd">

Then use local copy of the DTD where possible to improve speed.

This should help with character entity resolution. Of course this doesn't help with the problem of web browsers not performing DTD validation.

**Comment by Klortho** [comment]
Unfortunately, even using the full URL, as in your example, doesn't work, because the browser's XML parser doesn't "go outside" to resolve the DTD.  `&mdash;` still doesn't get resolved, and the parser fails.

**Comment by hubgit** [comment]
Maybe recommend passing the XML through `xmllint --loaddtd --valid input.xml` first (or provide a service to do so), to test well-formednessl, load the DTD and convert any named entities?

**Comment by vincentml** [comment]
For the DTD validation part it might be possible to use Schematron instead. [DTD Analyzer](http://dtd.nlm.nih.gov/ncbi/dtdanalyzer/) has this feature:

> dtdschematron.xsl - generates a schematron file from the DTD, including extra schematron rules (if present) from specially-formatted comments of the DTD

An XSLT solution might work to resolve character entities in a pre-processing step. First get all the character entity definitions in JATS DTD to one file to make a convenient lookup table. Create an XSLT that takes a given XML file provided as a parameter and outputs using text mode. A single template could use unparsed-text to find character entities and replace them with the numeric character reference equivalent from the lookup table. The output would be an XML file with all recognized character entities replaced by their NCR equivalents. Use this XML for further validation.

**Comment by Klortho** [comment]
I just discovered another, very nasty side-effect of the browser not reading the DTD. Both Safari and Chrome exhibit this behavior, but FF is better.

The DTDs contain default attribute values for the namespace pseudo-attributes. So, for example, this is valid if the parser reads the DTD:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article 
  PUBLIC "-//NLM//DTD JATS (Z39.96) Journal Publishing DTD v0.4 20110131//EN"
  "../dtd/JATS-journalpublishing0.dtd">
  
<article xmlns:mml='http://www.w3.org/1998/Math/MathML'>
  <front>
    <journal-meta>
      <journal-id></journal-id>
      <issn></issn>
    </journal-meta>
    <article-meta>
      <title-group>
        <article-title>Archival DTD Test Article</article-title>
        <subtitle>(Just a small one for parsing)</subtitle>
      </title-group>
      <pub-date>
        <year>2015</year>
      </pub-date>
    </article-meta>
  </front>
  <body>
    <p>The number of reservoir holes for this pattern is 
      <inline-formula id='M1'>
        <alternatives>
          <graphic xlink:href='foo'/>
          <tex-math>n^2</tex-math>
        </alternatives>
      </inline-formula>
    </p>
  </body>
</article>
```

Note the "xlink:" namespace prefix is defined in the DTD.  But the browser doesn't read the DTD, and in the case of Chrome and Safari, they just silently drop all of the content inside the \<alternatives> - not even any error indication (FF gives a parse error at least).

This had me pulling my hair out for the last two hours, thinking there was some bug in Saxon-CE, since it wasn't reporting errors that I expected.

**Comment by hubgit** [comment]
Is it possible to define namespaces in the schema like that when using an XSD schema, or only with a DTD?

I think it's probably best to ensure that the namespaces are defined in the document (and show a parse error if they're not).

**Comment by Klortho** [comment]
> Is it possible to define namespaces in the schema like that when using an XSD schema

No, I don't think so. DTDs don't really understand namespaces at all, and these namespace pseudo-attributes are defined as default attribute values in the DTD.

> I think it's probably best to ensure that the namespaces are defined in the document (and show a parse error if they're not).

I agree.

**Comment by Klortho** [comment]
I think this one can be closed now.  Many thanks to Alf for the JS port of xmllint!

See [this pull request](https://github.com/JATS4R/jats4r.github.io/pull/25).
