### ISSUE TITLE
Recommendation: equations and formulas should not be hidden in bitmap graphics

### ISSUE THREAD

**Issue by Daniel-Mietchen** [JATS4R/elements#7]
For an example, see https://github.com/wpoa/JATS-to-Mediawiki/issues/22#issuecomment-50207644 .

**Comment by Melissa37** [comment]
Are you referring to this:
https://github.com/JATS4R/elements/blob/master/math.md

eLife totally agrees to this recommendation

**Comment by Klortho** [comment]
Can we close this?  It seems that this already made it into [the draft recommendations](https://github.com/JATS4R/elements/wiki/Math), bullet point # 3.
