### ISSUE TITLE
Should we rename this repository?

### ISSUE THREAD

**Issue by Klortho** [JATS4R/elements#87]
Yesterday, in the telecon, it came up that the name “elements” for this repository is confusing – it doesn’t mean much. This repo contains all of our example files, our wiki (draft recommendations), and all of the issues that we use for discussing tagging. 

We could rename this, and it probably wouldn’t effect much (GitHub is good about making old links work even after repos have been renamed). 

Do we want to do this (I vote yes).  If so, what would be a good name? Here are two ideas:

* “tagging” - I like this, because it's very generic, short, and simple.
* “examples” - describes the content, but not the wiki or the issues. 

Other ideas?

**Comment by Melissa37** [comment]
I think examples - but would add "Live" examples.

**Comment by Klortho** [comment]
> ... but would add "Live" examples.

What do you mean?  You want the repo name to be live-examples (for example)?

**Comment by Melissa37** [comment]
That's the idea. It would indicate that they are not JATS4R approved, but what's out there in the live. But not sure whether it would make that distinction really clear?

**Comment by Klortho** [comment]
How about `tagging-examples`?

**Comment by Klortho** [comment]
We decided to rename it "JATS4R-Participant-Hub", so that it's clear that this is the central, "go-to" place for participants.
