### ISSUE TITLE
Document workflow for group's recommendations

### ISSUE THREAD

**Issue by Klortho** [JATS4R/elements#9]
The proposed recommendations are being drafted on the Wiki here.  What specific mechanism should we use to progress a page from "draft" through to "official"?  Example: https://github.com/JATS4R/elements/wiki/Permissions.

**Comment by Melissa37** [comment]
This looks good to eLife. Any comments from anyone else or should we close this issue and mark it as resolved?

**Comment by Klortho** [comment]
Can we keep this open for now?  I'd like to suggest a couple of changes to the page, and we can discuss them here -- GitHub, AFAIK, doesn't provide the ability to get notifications when a wiki page changes.

**Comment by Klortho** [comment]
As it mentions in the existing GH pages site, "As we finalize these recommendations, we will move them from the GitHub wiki into pages on this site."  I want to add details for how we go about moving them. I think that we should try to use gh pull requests, if possible, since it will give us an easy approval mechanism.

**Comment by Klortho** [comment]
Copying a comment that I just made on the JATS-Con paper draft:

> The plan is (as I understand it) that "publishing" the recommendations means migrating from the GitHub wiki to pages under the jats4r.github.io repo, where they will appear on our website. Many GH pages sites have an "edit button", which takes users to a fork of the site on GitHub. We can use Git tags to specify release versions. There are a lot of details to be worked out, of course.

**Comment by Melissa37** [comment]
review existing practices,
agree on best practice,
issue draft recommendations,
invite community feedback,
issue formal recommendations,
implement tools to help publishers identify whether their XML is compliant,
disseminate best practice tagging guidelines,
publish reports on compliance - where it can be determined.

I wonder whether the following steps could be amalgamated into one step:
issue formal recommendations,
implement tools to help publishers identify whether their XML is compliant,
disseminate best practice tagging guidelines,

The first and the third are the same, unless we are talking about publicising the guidelines further than our own website? Also, the tools should be available at the same time as issuing the formal recommendations. That's what we're doing right now with Permissions and Math, right?

**Comment by Melissa37** [comment]
Also add to GitHub repo a compliant example.
Change wording on site.
Then can close.

**Comment by Melissa37** [comment]
Wording on site changed

**Comment by Melissa37** [comment]
Agreed on call 16th April call to close this issue.
